services:
  api:
    build: ./backend
    container_name: kpinotepad-backend
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build: ./frontend
    container_name: kpinotepad-frontend
    volumes:
      - ./uploads/img:/usr/share/nginx/html/img/uploads:ro
    ports:
      - "80:80"
    depends_on:
      - api